version: '3'

services:
  interlok:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      JAVA_OPTS:
  nats:
    image: 'nats:2.1'
    hostname: 'nats-1'
#    ports:
#      - '4222:4222'
#      - '8222:8222'
